@startuml
left to right direction
package "ChoiChoi Reservation"{
    class "<<Application>>\nChoiChoiService" as ChoiChoiService{}

    class "<<Resource>>\nReservations" as ResourceReservations{
        <<GET>> +getReservations():Reservation
        <<POST>> +createReservation():Reservation
    }

    class "<<Resource>>\nReservation" as ResourceReservation {
        <<GET>> +getReservation(): Reservation
        <<PUT>> +updateReservation(): Reservation
        <<DELETE>> +deleteReservation(): void
    }

    class "<<Representation>>\nReservation" as RepresentationReservation {
        -date
        -user
        -shop
        -createdAt
    }

}

ChoiChoiService ..> ResourceReservations:"/Reservations\n<<Path>>"
ResourceReservations ..> ResourceReservation: "/{ReservationId}\n<<Path>>"
ResourceReservation ..> RepresentationReservation: "<<use>>"



@enduml